---
title: "index"
output: html_document
---


```{r include=FALSE}

library(googleVis)
library(dplyr)
library(rio)

### Renewable Energy Generation
solar <- import('https://raw.githubusercontent.com/Camila-RV/VieiraKhanna_Assignment3/master/data_raw/nrg_105a_1_Data.csv')
wind1 <- import('https://raw.githubusercontent.com/Camila-RV/VieiraKhanna_Assignment3/master/data_raw/nrg_105a_2_Data.csv')
wind2 <- import('https://raw.githubusercontent.com/Camila-RV/VieiraKhanna_Assignment3/master/data_raw/nrg_105a_3_Data.csv')
wind3 <- import('https://raw.githubusercontent.com/Camila-RV/VieiraKhanna_Assignment3/master/data_raw/nrg_105a_4_Data.csv')

#select the necessary columns
solar <- select(solar, GEO, TIME, Value)
wind1 <- select(wind1, GEO, TIME, Value)
wind2 <- select(wind2, GEO, TIME, Value)
wind3 <- select(wind3, GEO, TIME, Value)

#assigning numeric variable

solar[,'Value'] <- as.numeric(gsub(",", "",solar[,'Value'])) # gsub replaces "," in numbers to "" before converting them to numeric
wind1[,'Value'] <- as.numeric(gsub(",", "",wind1[,'Value']))
wind2[,'Value'] <- as.numeric(gsub(",", "",wind2[,'Value'])) 
wind3[,'Value'] <- as.numeric(gsub(",", "",wind3[,'Value']))

#creating dependent variables
re_generation <- merge(wind1, wind2, by = c('GEO', 'TIME'), all.x = T)
re_generation <- merge(re_generation, wind3 , by = c('GEO', 'TIME'), all.x = T)
re_generation$wind_gen <- re_generation$Value.x+ re_generation$Value.y+ re_generation$Value
re_generation <- select(re_generation, GEO, TIME, wind_gen)
re_generation <- merge(re_generation, solar, by = c('GEO', 'TIME'), all.x = T)
names(re_generation)[4] <- "solar_gen" 
re_generation$re_gen <- re_generation$wind_gen + re_generation$solar_gen
names(re_generation)[1] <- "country"
re_generation$country[re_generation$country == "Germany (until 1990 former territory of the FRG)" ] <- "Germany"

re_generation <- re_generation[which(re_generation$TIME == "2013"),]
re_generation <- select(re_generation, re_gen, country)



```


```{r results='asis', echo=FALSE}

# Plot
re_map <- gvisGeoChart(re_generation, locationvar = 'country',
                      colorvar = 're_gen',
                      options = list(
                        colors = "['#fff7bc', '#d95f0e']",
                        region ="150"
                          ))

print(re_map, tag = 'chart')

```

